name: A workflow to build books using Enki
on: push
jobs:
  build:
    name: Build book with Enki.
    runs-on: ubuntu-latest
    container: samuelklutse/enki_epub:latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Set Env variables
        run: |
          echo "TAG=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
          echo "WORKDIR=/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Build Book
        run: |
          echo 'Initializing Book Build'
          cd /github
          git clone https://github.com/openstax/enki
          cd enki
          git checkout sk-epub-fixes 
          TRACE_ON=1 LOCAL_ATTIC_DIR=_attic TERM=xterm /github/enki/dockerfiles/enki-in-container --command all-git-epub --repo-dir ${{ env.WORKDIR }} --style dummy --book-slug 'book-slug1' 

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          dry_run: true
          release_branches: action-a
          github_token: ${{ secrets.GITHUB_TOKEN }}

#
