name: A workflow to build books using Enki
on: push
jobs:
  build:
    name: Build book with Enki.
    runs-on: ubuntu-latest
    container: samuelklutse/enki_epub:latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Checkout repository
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls -alt ${{ env.WORKDIR }}
      - name: Build Book
        run: |
          echo 'Initializing Book Build'
          cd /github
          git clone https://github.com/openstax/enki
          cd enki
          git checkout sk-epub-fixes 
          TRACE_ON=1 LOCAL_ATTIC_DIR=_attic TERM=xterm /github/enki/dockerfiles/enki-in-container --command all-git-pdf --repo-dir ${{ env.WORKDIR }} --style dummy
          

