name: A workflow to build books using Enki
on: push
jobs:
  build:
    name: Build book with Enki.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/build
        with:
          REPO_NAME: ${{ github.repository }}
          REPO_PATH: ${{ github.workspace }}
