name: A workflow to build books using Enki
on: push
jobs:
  build:
    name: Build book with Enki.
    runs-on: ubuntu-latest
    container: samuelklutse/enki_epub:latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Set Env variables
        run: |
          echo "TAG=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
          echo "WORKDIR=/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          release_branches: action-a
          github_token: ${{ secrets.GITHUB_TOKEN }}

#
